# Generated by Django 5.2.5 on 2025-10-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Bills', 'Bills'), ('Rent', 'Rent'), ('Transport', 'Transport'), ('Other', 'Other')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service', models.CharField(choices=[('OPD', 'OPD'), ('Labs', 'Labs'), ('CT', 'CT'), ('MRI', 'MRI'), ('Endoscopy', 'Endoscopy'), ('EU Diagnostics', 'EU Diagnostics'), ('ERCP', 'ERCP'), ('EUS Interventional', 'EUS Interventional'), ('ANCILLARY SERVICES', 'ANCILLARY SERVICES')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Paid', max_length=20)),
            ],
        ),
    ]
