# Generated by Django 5.2.5 on 2025-10-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Bills', 'Bills'), ('Rent', 'Rent'), ('Transport', 'Transport'), ('Other', 'Other')], default='other', max_length=50),
        ),
    ]
